eureka:
  client:
    registryFetchIntervalSeconds: 5  # default 30
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5  # default 30
    leaseExpirationDurationInSeconds: 10 # default 90

management:
  endpoints:
    web:
      exposure:
        include: health, shutdown
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
      gatewayLevelCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      userServiceRetry:
        maxAttempts: 3
        waitDuration: 2s
        intervalFunction:
          type: exponentialBackoff
          initialInterval: 2s
          multiplier: 2
          maxInterval: 5s
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException$NotFound
#      gatewayLevelRetry:
#        maxAttempts: 3
#        waitDuration: 5s
#        exponentialBackoffMultiplier: 2
  rateLimiter:
    instances:
      userServiceRateLimiter:
        limitForPeriod: 2 # no. of calls that are allowed during the refresh period. 2 api allowed in 1 second
        limitRefreshPeriod: 1s # every given second time period refresh the limit
        timeoutDuration: 0 # how many milli seconds to wait if reach limit. 0 means no wait, immediately reject.
