spring:
  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/booking/**
#          filters:
#            - RewritePath=/api/booking/(?<segment>.*), /booking/${segment} # This is also same as below
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}
            - name: CircuitBreaker
              args:
                name: gatewayLevelCircuitBreaker
                fallbackUri: forward:/fallback/booking
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/account/**
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**

gateway:
  open-paths:
    - /auth/login
    - /public/**
    - /api/v1/account/user/create
    - /actuator/**


jwt:
  secret: gnr4ng458hjtg80459gh458g4580jg45rg

logging:
  level:
    root: info
    org.hibernate.SQL: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
